---
title: "Indicator_species"
author: "Liupf"
date: "3/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

#sources
```
https://rdrr.io/cran/labdsv/man/indval.html
indval: Dufrene-Legendre Indicator Species Analysis
In labdsv: Ordination and Multivariate Analysis for Ecology
http://rfunctions.blogspot.com/2013/02/multivariate-analysis-indicator-value.html
```

```{R}
# First, download 'DoubsSpe.csv' data file:

# https://www.mediafire.com/file/9xo1iplg6sc3c1q/DoubsSpe.csv/file

# It has species in columns and samples in rows. Note that the first column indicates the type of habitat in which the species were sampled. Ok, now load 'DoubsSpe.csv' file into R:

samples <- read.csv(choose.files(),sep=",",row.names=1)

### maybe you need to change the argument   sep=","   to   sep=";" . ###
```

```{r}
# Install the package "labdsv" and load it:

install.packages("labdsv") # this way to download the package is not supported on all versions of R, ok?
library (labdsv)
```

```{r}
# Calculate Indicator Values for species:
iva <- indval(samples[,-1], samples[,1]) # Note that we removed the first column of the file on the first argument, because the types of sites are put on the second one.
iva # Open the file to see the information generated by the function

```

```{r}
#Extra: You can use the K-Means clustering method ('kmeans' function; see my other post about it) to generate groups if you have quantitative values for regions and want to define different types of habitat.

# Now, use this to gather only the most important iformation (if you are using a file with another name, change 'samples[,-1]' to "your file[,-1]"):


gr <- iva$maxcls[iva$pval<=0.05]
iv <- iva$indcls[iva$pval<=0.05]
pv <- iva$pval[iva$pval<=0.05]
fr <- apply(samples[,-1]>0, 2, sum)[iva$pval<=0.05]
indvalsummary <- data.frame(group=gr, indval=iv, pvalue=pv, freq=fr)
indvalsummary <- indvalsummary[order(indvalsummary$group, -indvalsummary$indval),]

# Let us see the results
indvalsummary



```

## questions
**could we extract which species is the indicator species in addition to the numbers**
```{r}


```

```{r}


```

```{r}


```

```{r}


```